---
title: Cheat Sheet
---

# Cylindrische Coördinaten

$x=r\cos\theta$

$y=r\sin\theta$

$z=z$

$r^2=x^2+y^2$

$\tan\theta=\dfrac{y}{x}$

$dV=r\ dr\ d\theta\ dz$

# Bolcoördinaten

$x=R\sin\varphi\cos\theta$

$y=R\sin\varphi\sin\theta$

$z=R\cos\phi$

$R^2=x^2+y^2+z^2=r^2+z^2$

$r=\sqrt{x^2+y^2}=R\sin\varphi$

$\tan\varphi=\dfrac{r}{z}=\dfrac{\sqrt{x^2+y^2}}{z}$

$\tan\theta=\dfrac{y}{x}$

$dV=R^2\sin\varphi\ dR\ d\varphi\ d\theta$

# Veldlijnen

$$\dfrac{dx}{F_1(x,y,z)}=\dfrac{dy}{F_2(x,y,z)}=\dfrac{dz}{F_3(x,y,z)}$$

# Basisvectoren

$\hat{r}=\cos\theta\hat{i}+\sin\theta\hat{j}$

$\hat{\theta}=-\sin\theta\hat{i}+\cos\theta\hat{j}$

# Conservatief veld

$\mathbf{F}(x,y,z)=\nabla\varphi(x,y,z)$

$\dfrac{\partial}{\partial y}F_1(x,y)=\dfrac{\partial}{\partial x}F_2(x,y)$

$\dfrac{\partial F_1}{\partial y}=\dfrac{\partial F_2}{\partial x},\dfrac{\partial F_1}{\partial z}=\dfrac{\partial F_3}{\partial x},\dfrac{\partial F_2}{\partial z}=\dfrac{\partial F_3}{\partial y}$

$\begin{vmatrix}\hat{i}&\hat{j}&\hat{k}\\\dfrac{\partial}{\partial x}&\dfrac{\partial}{\partial y}&\dfrac{\partial}{\partial z}\\F_1&F_2&F_3\end{vmatrix}=\vec{0}$
