---
title: Over mij
author: Wout Notermans
date: '2022-10-01'
slug: [about]
ShowToC: false
---

Ik ben Wout Notermans, student wiskunde en computer nerd uit België. Mijn voornaamste interesses zijn computationele en toegepaste wiskunde, met een extra focus op programmeren en optimalisatie. Daarbuiten ben ik muzikant, ik bespeel het [*eufonium*](https://nl.wikipedia.org/wiki/Eufonium) al bijna mijn hele leven. Ik luister voornamelijk naar eurobeat, video game OST en jazz, al ben ik ook een grote fan van oude musicals zoals *Singin' In The Rain*. Ik [programmeer](/nl/projects) voornamelijk in [Python](https://www.python.org/), maar ik ben van plan om ook [Lua](https://www.lua.org/) te leren voor zijn extreme snelheid.

# Over deze website

Deze website werd gemaakt met behulp van [blogdown](https://bookdown.org/yihui/blogdown/), een R package die het mogelijk maakt op een eenvoudige manier (R) Markdown bestanden om te zetten naar HTML via [Hugo](https://gohugo.io/). Het thema is gebaseerd op [PaperMod](https://github.com/adityatelange/hugo-PaperMod/) van [Aditya Telange](https://github.com/adityatelange), met een paar van mijn eigen aanpassingen. De source code is terug te vinden op [mijn github](https://github.com/wnotermans/woutnotermans.be).
