---
output:
  pdf_document:
    includes:
      in_header: header.tex
---

# Hoofdstuk 1: Kansruimten

## Definitie 1.1

Universum: verzameling van alle mogelijke uitkomsten van een experiment. Notatie: $\Omega$. De elementen van $\Omega$ noteren we door $\omega$.

## Definitie 1.3

Sigma-algebra: een $\sigma$-algebra $\mathcal{B}$ over een universum $\Omega$ is een niet-lege familie van deelverzamelingen van $\Omega$, zodat:

\- [B1]: $A\in\mathcal{B}\implies A^c\in\mathcal{B}$

\- [B2]: $A_n\in B,n=1,2,...\implies\cup_{n=1}^{\infty}A_n\in\mathcal{B}.$

Een universum $\Omega$ uitgerust met een $\sigma$-algebra $\mathcal{B}$ is een **meetbare ruimte** $(\Omega,\mathcal{B})$.

## Definitie 1.5

De $\sigma$-algebra $\mathcal{B(C)}$ gedefinieerd door [Stelling 1.4](/nl/school/fundamenten/st-eig-etc#stelling-14) heet: de $\sigma$-algebra voortgebracht door de klasse $\mathcal{C}$.

## Definitie 1.6

Een kansmaat $P$ op $\mathcal{B}$ is een functie $$P:\mathcal{B}\to\mathbb{R}$$ $$A\mapsto P(A)$$ zodanig dat:

\- [P1]: $P(\Omega)=1$

\- [P2]: voor alle $A\in\mathcal{B}:P(A)\geq0$

\- [P3]: (axioma der **aftelbare additiviteit**): voor $A_n\in\mathcal{B},n=1,2,...,$ paarsgewijs disjunct, geldt: $$P\left(\cup_{n=1}^{\infty}A_n\right)=\sum_{n=1}^{\infty}P(A_n)$$

## Definitie 1.8

Een drietal $(\Omega,\mathcal{B},P)$ heet een **kansruimte**.

# Hoofdstuk 2: Voorwaardelijke kans en onafhankelijkheid

## Definitie 2.1

Zij $(\Omega,\mathcal{B},P)$ een kansruimte. Zij $B\in\mathcal{B}$ met $P(B)>0$. De **voorwaardelijke kans van** $A\in\mathcal{B}$**, gegeven** $B$ wordt genoteerd door $P(A|B)$ en gedefinieerd door $$P(A|B)=\dfrac{P(A\cap B)}{P(B)}.$$Voor $P(B)=0$ is $P(A|B)$ niet gedefinieerd.

## Definitie 2.4

Twee gebeurtenissen $A$ en $B$ heten **onafhankelijk** indien $$P(A\cap B)=P(A)\cdot P(B).$$

## Definitie 2.5

Een familie gebeurtenissen $A_1,A_2,...,A_n;(n\geq2)$ heet **onderling onafhankelijk** indien voor **elke** keuze van r verschillende indices $i_1,i_2,...,i_r$ uit $1,...,n$ en voor elke $r=2,...,n$ geldt: $$P(A_{i_1}\cap A_{i_2}\cap\ldots\cap A_{i_r})=P(A_{i_2})P(A_{i_2})\cdots P(A_{i_r}).$$

## Definitie 2.6

Een oneindige familie gebeurtenissen $A_1,A_2,...$ heet onderling onafhankelijk indien elke eindige deelfamilie onderling onafhankelijk is in de zin van [Definitie 2.5](#definitie-25).

# Hoofdstuk 3: Stochastische veranderlijken en hun verdeling

# Hoofdstuk 4: Verwachtingswaarde; momenten; genererende functie; karakteristieke functie

# Hoofdstuk 5: Meerdimensionale verdelingen

# Hoofdstuk 6: Voorwaardelijke verdelingen en verwachtingwaarden

# Hoofdstuk 7: Transformaties van stochastische veranderlijken

# Hoofdstuk 8: Convergentie van stochastische veranderlijken

# Hoofdstuk 9: Steekproeven uit een populatie

# Hoofdstuk 10: Schattingsproblemen
