---
title: "Begrippenlijst"
output:
  pdf_document:
    includes:
      in_header: header.tex
---

# Hoofdstuk 1: Basisbegrippen

## Definitie 1.1.1

\- Analytische/holomorfe functie: een functie $f:\Omega\to\mathbb{C}$ is een analytische/holomorfe functie in $\Omega$ als ze in elk punt $z_0\in\Omega$ complex differentieerbaar is en indien $f'$ continu is.

\- Complex differentieerbaar: $$\lim_{z\to z_0}\dfrac{f(z)-f(z_0)}{z-z_0}=:f'(z)$$ bestaat in $\mathbb{C}$.

## Definitie 1.1.5

\- Harmonische functie: Een functie $f:\Omega\subset\mathbb{R}^2\to\mathbb{R}$ heet **harmonisch** indien $\nabla^2\varphi=0$, met $\nabla^2$ de **Laplaciaan**, d.i. $$\nabla^2\varphi=\dfrac{\partial^2\varphi}{\partial x^2}+\dfrac{\partial^2\varphi}{\partial y^2}$$

\- Harmonisch toegevoegde: Een functie $v(x,y)$ heet het harmonisch toegevoegde van harmonisch functie $u(x,y)$ indien $u$ en $v$ voldoen aan de vergelijkingen van Cauchy-Riemann.

## Definitie 1.2.1

Zij $f:\Omega\to\mathbb{C}$ continu en zij $\mathcal{C}\subset\Omega$ een kromme met bijbehorende parametrisatie $z=\sigma(t),\ t\in[a,b]$. We definiëren en noteren de **lijnintegraal** van $f$ langs $\mathcal{C}$ door: $$\int_\mathcal{C}f(z)dz=\int_a^bf(\sigma(t))\sigma'(t)dt$$. ook wel genoteerd door $\int_\sigma f(z)dz$. Indien $\mathcal{C}$ een gesloten kromme is noteren we vaak door $\oint_\mathcal{C}f(z)dz$.

# Hoofdstuk 2: De representatieformule van Cauchy

# Hoofdstuk 3: Enige meetkunde in $\mathbb{C}$

# Hoofdstuk 4: Nulpunten, singuliere punten

# Hoofdstuk 5: Evaluatie van integralen

# Hoofdstuk 6: Conforme transformaties

# Hoofdstuk 7: Aanvullende begrippen
